Update docker-build.yml after error by build action
Action raised error:
ERROR: invalid tag "ghcr.io/Tom-Bom-badil/ugreen-api-token:latest": repository name must be lowercase
Error: buildx failed with: ERROR: invalid tag "ghcr.io/Tom-Bom-badil/ugreen-api-token:latest": repository name must be lowercase

Changed to lower case; not sure if it is case sensitive, though _(try-and-error)_.